export const types = {
    SET_VEHICLES : "SET_VEHICLES",
    SET_SEARCH_BAR_VISIBILITY: "SET_SEARCH_BAR_VISIBILITY",
    SET_RESERVATION: "SET_RESERVATION",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILED:"LOGIN_FAILED",
    LOGOUT:"LOGOUT"
}